### ISSUE TITLE
Check last official Falcon version && Separately implementation 😏

### ISSUE THREAD

**Issue by leonbakadorov** [GramThanos/falcon.js#2]
Following issue #1 

Falcon is a promising algorithm for post-quantum cryptography, has become a finalist in the NIST competition and is approved for inclusion in the standardization. 😎

Your implementation is a perfect example of what it should look like. 👍

1. Can you check the official latest version of Falcon? If so, how long can we expect you to release an updated version of your implementation? ✨

2. Since you have implemented WASM or JS, could you also implement them separately so that you can simply connect the .js file and use it? 📑

With best regards.

**Comment by GramThanos** [comment]
Regarding question 1:

It is in my future plans to upgrade this project to the latest version of Falcon as well as improve its API. But no from my side ETA. It is probably not much work, but nevertheless I have to find the time to do it.

With that been said, all the code is here and any person with a bit of linux experience and understanding could update the code and compile it from source.

Regarding question 2:

The best approach is to always load the JavaScript version and before using it, check if the wasm is also available. Thus, to support your needs, it is better to add an option just to skip this step and just use the JavaScript version.
