### ISSUE TITLE
RND is not random on the current compiled version

### ISSUE THREAD

**Issue by leonbakadorov** [GramThanos/falcon.js#3]
I was confused by the fact that when the page is opened, the same key pair is always generated. But later I found out that the values generated are completely non-unique - they are simply displayed in order. First the first pair of keys, then the second and so on. THIS IS HOW TO UNDERSTAND AT ALL?

**Comment by GramThanos** [comment]
This is probably a bug of the emscripten version used to compile the current live version of the library.

Some more info: Currently inside the manifest it's specified that emscrypten should use `Math.random` (which may not be secure for cryptographically actions but is sufficient at the JavaScript level for a client implementation like this where the context where the JavaScript is executed is considered secure). Though it seems emscripten not to use `Math.random` for some reason.

**Comment by leonbakadorov** [comment]
What does Math.random have to do with it? The essence of Falcon is to always generate completely random cryptographically strong key pairs, as well as an almost infinite number of signatures. How could you post it if it doesn't work on a fundamental level?

I'm shocked.

**Comment by GramThanos** [comment]
Technically, Falcon as an algorithm has nothing to do with generating random keys.

Going back to your question regarding Math.random, this project is based on emscripten and the official release of Falcon for the NIST round 3, which includes a RNG based on `/dev/urandom` to generate random keys. It seems that this `/dev/urandom` is not linked correctly with the `Math.random` as it should as described by the documentation of Emscripten.

**Comment by GramThanos** [comment]
Bug fixed.
