### ISSUE TITLE
How powerful is a 256 signature?

### ISSUE THREAD

**Issue by leonbakadorov** [GramThanos/falcon.js#4]
As the minimum 512 is shown on the official website, other sources recommend using at least 512. Now I'm wondering how reliable the 256 signature is?

**Comment by GramThanos** [comment]
You can take a look into the [Specification](https://falcon-sign.info/falcon.pdf), specifically under 2.6 Summary of Parameters.
The official release was submitted to the NIST competition and 2 security levels were suggested based on the NIST levels:
 - Falcon-512 targeting NIST security Level I
 - Falcon-1024 targeting NIST security Level V

Thus, to sum up, in terms of reliability, 256 ring degree (n) reliability is just fine. The only thing that changes between the deferent values of n is the security level. Depending on your application, security requirements and your projects policies you may aim for a specific security level.

**Comment by leonbakadorov** [comment]
Falcon 512 is similar in terms of security to AES 256.

It turns out that Falcon 256 is similar to AES 128?

**Comment by GramThanos** [comment]
> Falcon 512 is similar in terms of security to AES 256.
> 
> It turns out that Falcon 256 is similar to AES 128?

To start with, Falcon is used for signing thus comparing it to AES (used for encrypting) is wrong. 

The creators chose to compare it with RSA, and mention on their website:
> To give a point of comparison, Falcon-512 is roughly equivalent, in classical security terms, to RSA-2048, whose signatures and public keys use 256 bytes each

Assuming that this claim is correct, and as we see that the signatures and key sizes on Falcon scale in a similar way, on could assume that Falcon 256 is equivalent to RSA-1024, and Falcon 1024 is equivalent to RSA-4096.

Furthermore, here is a related quote from the code:
> Falcon is parameterized by a degree, which is a power of two. Formally, two values are possible: 512 and 1024 (for Falcon-512 and Falcon-1024, respectively). This implementation also supports lower degrees, from 2 to 256; these reduced variants do not provide adequate security and should be used for research purposes only.

Additionally, one should also take into consideration that SHAKE256 is used by the code internally.
